import { exp } from "react-native-reanimated";

// get cites in country
export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL';

// get tours in city
export const GET_TOURS = 'GET_TOURS';
export const GET_TOURS_SUCCESS = 'GET_TOURS_SUCCESS';
export const GET_TOURS_FAIL = 'GET_TOURS_FAIL';

//get traveler
export const GET_TRAVELER = 'GET_TRAVELER';
export const GET_TRAVELER_SUCCESS = 'GET_TRAVELER_SUCCESS';
export const GET_TRAVELER_FAIL = 'GET_TRAVELER_FAIL'

// login
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_FAIL = 'LOGIN_ACCOUNT_FAIL';

//login facebook
export const LOGIN_FACEBOOK = 'LOGIN_FACEBOOK';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_FAIL = 'LOGIN_FACEBOOK_FAIL';

//login gmail
export const LOGIN_GMAIL = 'LOGIN_GMAIL';
export const LOGIN_GMAIL_SUCCESS = 'LOGIN_GMAIL_SUCCESS';
export const LOGIN_GMAIL_FAIL = 'LOGIN_GMAIL_FAIL';

//register
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';
export const REGISTER_ACCOUNT_FAIL = 'REGISTER_ACCOUNT_FAIL';

// update profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

// get question tour guide
export const GET_QUESTION_ACTIVE = 'GET_QUESTION_ACTIVE';
export const GET_QUESTION_ACTIVE_SUCCESS = 'GET_QUESTION_ACTIVE_SUCCESS';
export const GET_QUESTION_ACTIVE_FAIL = 'GET_QUESTION_ACTIVE_FAIL';

// push question tour guide
export const PUSH_QUESTIONS = 'PUSH_QUESTIONS';
export const PUSH_QUESTIONS_SUCCESS = 'PUSH_QUESTIONS_SUCCESS';
export const PUSH_QUESTIONS_FAIL = 'PUSH_QUESTIONS_FAIL';

// get tour guide
export const GET_TOUR_GUIDE = 'GET_TOUR_GUIDE';
export const GET_TOUR_GUIDE_SUCCESS = 'GET_TOUR_GUIDE_SUCCESS';
export const GET_TOUR_GUIDE_FAIL = 'GET_TOUR_GUIDE_FAIL';

// update item tour guide
export const UPDATE_ITEM_TOUR_GUIDE = 'UPDATE_ITEM_TOUR_GUIDE';
export const UPDATE_ITEM_TOUR_GUIDE_SUCCESS = 'UPDATE_ITEM_TOUR_GUIDE_SUCCESS';
export const UPDATE_ITEM_TOUR_GUIDE_FAIL = 'UPDATE_ITEM_TOUR_GUIDE_FAIL';