// Sign Up
export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Sign In
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// get data vietnam
export const GET_DATA_VIETNAM = 'GET_DATA_VIETNAM';
export const GET_DATA_VIETNAM_SUCCESS = 'GET_DATA_VIETNAM_SUCCESS';
export const GET_DATA_VIETNAM_FAIL = 'GET_DATA_VIETNAM_FAIL';

// get data tour guides
export const GET_DATA_TOUR_GUIDES = 'GET_DATA_TOUR_GUIDES';
export const GET_DATA_TOUR_GUIDES_SUCCESS = 'GET_DATA_TOUR_GUIDES_SUCCESS';
export const GET_DATA_TOUR_GUIDES_FAIL = 'GET_DATA_TOUR_GUIDES_FAIL';