require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CapstoneVersion2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  target 'CapstoneVersion2Tests' do
    inherit! :complete
    # Pods for testing
  end
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  
  
  # Override Firebase SDK Version
  $FirebaseSDKVersion = '6.29.0'
  $RNFirebaseAsStaticFramework = true

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
         end
      end
  end
  end
end

target 'CapstoneVersion2-tvOS' do
  # Pods for CapstoneVersion2-tvOS

  target 'CapstoneVersion2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end